apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification-service
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003
      nodePort: 30004
  type: NodePort 
