apiVersion: apps/v1
kind: Deployment
metadata:
  name: reporting-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reporting-service
  template:
    metadata:
      labels:
        app: reporting-service
    spec:
      containers:
      - name: reporting-service
        image: xhassanzx/mini-instapay-reporting-service:latest
        ports:
        - containerPort: 8002
        env:
        - name: CORS_ALLOWED_ORIGINS
          value: "http://192.168.58.2:30000"
