# Generated by Django 5.1.7 on 2025-05-15 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Transactions",
            new_name="Logs",
        ),
    ]
